### ISSUE TITLE
Add draggable width to Articles' column

### ISSUE THREAD

**Issue by notnsane** [Worldbeater/myFeed#1]
We could really use more width to have better usage of the horizontal space, [so things like these won't happen](http://i.imgur.com/RJAOJgs.png).

**Comment by Worldbeater** [comment]
Hi, @notnsane! Thank you for your interest in myFeed development.

I've created adaptive layout for 'all feeds' and 'favorite feeds' pages in myFeed 2.0.1.0 update. So now, when application window width changes, column widths are recalculated and proportions are restored (currently set to 4/9 for all articles list column and chosen article contents column respectively). 

Please notify me if this does not solve the problem and certain width customization options should be added!
