### ISSUE TITLE
"Open in a web browser" function doesn't work with a complex feed

### ISSUE THREAD

**Issue by notnsane** [Worldbeater/myFeed#2]
I use [this feed link](https://www.reddit.com/search.rss?q=subreddit%3Agamedeals+free+NOT+(store+OR+drm+OR+weekend+OR+sale+OR+shipping)&sort=new&t=all) to be aware of game deals. When I click on "Open in a web browser", I get an error.

**Comment by Worldbeater** [comment]
Hmm, this bug does not seem to exist in myFeed 2.0 -- I tried to reproduce the issue, but did not succeed; the _open in web browser_ button seems to work as expected now. Please let me know if you come across it again!
