### ISSUE TITLE
No way to import or export OPML data

### ISSUE THREAD

**Issue by notnsane** [Worldbeater/myFeed#4]
Just as a way to make backups or import them.

BTW I think this reader has the most potential of them all, I've trying to find a good usable feed reader since 2 years ago and I'm still using one from 2009.

**Comment by Worldbeater** [comment]
Added option to export or import OPML data in myFeed v2.0.2.0 (will be available soon in Windows Store)! Import/export settings can be found in the _Settings -> Special_ section.
