### ISSUE TITLE
Binding to x:Bind?

### ISSUE THREAD

**Issue by touseefbsb** [worldbeater/MyFeed#6]
since uwp promotes the use of x:Bind and also there have been some new features in x:Bind with October 2018 SDK release, is it possible that Reactive UI can bind with x:Bind, instead of old Binding syntax?

**Comment by worldbeater** [comment]
Hi @touseefbsb and thank you for your interest! 

I can say yes, `{x:Bind}` and even `{Binding}` markup extensions are fully compatible with ReactiveUI. See <a href="https://github.com/worldbeater/ReactiveMvvm/tree/master/ReactiveMvvm.Uwp/Views">another example</a> demonstrating how to use `{x:Bind}` with UWP views. Using `{x:Bind}` for <a href="https://github.com/worldbeater/ReactiveMvvm/tree/master/ReactiveMvvm.Uwp/Views">simple scenarios</a> and <a href="https://reactiveui.net/docs/handbook/when-activated/">WhenActivated</a> + <a href="https://reactiveui.net/docs/handbook/events/">Events</a> (see <a href="https://reactiveui.net/docs/getting-started/installation/nuget-packages/#universal-windows-platform">packages page</a>) for complex ones is also a good practice, MyFeed application just demonstrates how to use various ReactiveUI features including type-safe bindings.

**Comment by touseefbsb** [comment]
so in theory I can do a straight swap in xaml in MyFeed app from **Binding** to **x:Bind** and it will just work? if that is the case would you consider upgrading the project to x:Bind, also what if I want to do oneway or two-way binding with x:Bind, no extra effort required? ( extra code to notify the change of property. )

**Comment by worldbeater** [comment]
As for now, the app is not using markup bindings to bind View properties to ViewModel properties at all. Instead, MyFeed uses <a href="https://reactiveui.net/docs/handbook/views/">code-behind type-safe ReactiveUI bindings</a> for illustrative purposes (see <a href="https://github.com/worldbeater/MyFeed/blob/master/MyFeed.Uwp/Views/FeedGroupView.xaml.cs#L21">an example</a>). But in theory, those code-behind bindings can be easily replaced with `x:Bind` markup bindings. 

The app uses old-style `Binding`s only with converters responsible for localization. I guess replacing that old `Binding` syntax to `x:Bind` should just work for this particular case.

Speaking about adding extra code to notify the UI about property changes, the app already uses such code at the ViewModel layer — <a href="https://github.com/Fody/PropertyChanged">PropertyChanged.Fody</a> injects `INotifyPropertyChanged` implementation at build time.

**Comment by touseefbsb** [comment]
ok, thanks for the clarification. the description says this project is baed upon Reactive UI, 8.0 version, and 9.0.1 is already released, is there any architectural differences between these 2 versions?

**Comment by worldbeater** [comment]
<a href="https://github.com/reactiveui/ReactiveUI/blob/master/src/ReactiveUI/ReactiveUI.csproj#L3">ReactiveUI 9.0.1</a> supports only .NET Standard 2.0+ versions, and <a href="https://blogs.msdn.microsoft.com/dotnet/2017/10/10/announcing-uwp-support-for-net-standard-2-0/">Universal Windows Platform supports .NET Standard 2.0 only starting with Fall Creators Update</a>. This means that if we'd like to use .NET Standard 2.0, we'll be unable to support good old Microsoft Lumia devices, such as Lumia 930, 640, etc. There are also <a href="https://goo.gl/EpUR6v">issues with Surface Hubs support</a>. But, if you don't need to run your app on those devices, 9.0.1 version is definitely a right way to go.

**Comment by touseefbsb** [comment]
hmm interesting, thanks for all the info, is there a video turorial series for reactive ui with UWP, that I can follow, I am new to reactive programming in general and have been doing uwp for a long time with traditional mvvm, and I want to follow best practices for this.

**Comment by worldbeater** [comment]
@touseefbsb I can suggest a great video tutorial made by Kent Boogaart — <a href="https://github.com/kentcb/WorkoutWotch#where-are-the-videos">Building an iOS app with C#</a> describing how to build an app using XAML and Xamarin.Forms; and his book <a href="https://kent-boogaart.com/you-i-and-reactiveui/">You, I and ReactiveUI</a>. These tutorials are all not about UWP, but the core concepts mentioned there actually apply to **all** platforms ReactiveUI framework supports. Personally I learned ReactiveUI following those tutorials and also reading the <a href="https://reactiveui.net/docs/handbook/">ReactiveUI Handbook</a>.

**Comment by touseefbsb** [comment]
thanks for all the links :)
